# This is a basic workflow to help you get started with Actions
name: CxFlow
 
# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
 
on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]
 
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
 
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
 
      # Cxflow Action
      - name: Checkmarx CxFlow Action
        # You may pin to the exact commit or the version.
        uses: checkmarx-ts/checkmarx-cxflow-github-action@v1.0-9.x
        with:
          # Provide Checkmarx URL
          checkmarx_url: https://cxapactrial.checkmarx.net/
          # Provide team
          team: /CxServer/SP/APAC
          # Provide Checkmarx Username
          checkmarx_username:  harshgokani
          # Provide Checkmarx Password
          checkmarx_password: Hdg1234!@#$
          # Provide Checkmarx Client Secret
          checkmarx_client_secret: 014DF517-39D1-4453-B7B3-9930C563627C
          # Select a Checkmarx Project
          project: Github_Actions_Piramal
          # Select a Checkmarx Preset
          #preset: # optional, default is Checkmarx Default
          # Break build based on Checkmarx findings?
          #break_build: # optional
         # GitHub API Token (note: you don't have to create secrets.GITHUB_TOKEN, it is created automatically and will not appear in your repo's custom secrets)
          github_token: ${{secrets.GITHUB_TOKEN}}
